on:
  push:
    branches: [main]
    paths:
      - "lib.typ"
      - "template/*"
      - ".github/workflows/ci.yml"
      - ".pre-commit-config.yaml"
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run prek
        uses: j178/prek-action@v1

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup fonts
        uses: ./.github/actions/setup-fonts
        with:
          manifest-path: manifest.yml
          font-awesome-version: "7.1.0"

      - name: Setup Just
        uses: extractions/setup-just@v3

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile
        run: just

      - name: Upload CV artifact
        uses: actions/upload-artifact@v4
        with:
          name: neat_cv_pdf
          path: template/*.pdf
          retention-days: 7
